import testimonial from './testimonial'
import portfolio from './portfolio'
import blogPost from './blogPost'
import faq from './faq'
import pageSection from './pageSection'
import siteSettings from './siteSettings'
import homepageSettings from './homepageSettings'
import welcomeSection from './sections/welcomeSection'
import heroSlider from './sections/heroSlider'
import heroCaption from './sections/heroCaption'
import featuredSection from './sections/featuredSection'
import processSection from './sections/processSection'
import soloHeroImage from './sections/soloHeroImage'
import whyChooseSection from './sections/whyChooseSection'
import homepageFaqs from './sections/homepageFaqs'
import codeSettings from './codeSettings'
import footerSettings from './footerSettings'
import socialSettings from './socialSettings'
import aboutSettings from './aboutSettings'

export const schemaTypes = [siteSettings, homepageSettings, aboutSettings, codeSettings, footerSettings, socialSettings, heroSlider, heroCaption, welcomeSection, featuredSection, processSection, soloHeroImage, whyChooseSection, homepageFaqs, testimonial, portfolio, blogPost, faq, pageSection]
